#!/bin/bash

#Launch SITL Instance
/usr/local/bin/dronekit-sitl copter --home=34.71264951115481,-77.216325690460220,0,180&

sleep 5

#Launch QGroundControl
/usr/local/bin/QGC.AppImage 2>/dev/null&

sleep 5

##Start MAVProxy
screen -dm mavproxy.py --master=tcp:127.0.0.1:5760 --out=127.0.0.1:14550 --out=127.0.0.1:5762

##Launch the dronekit-python script
/usr/bin/python "$1" --connect 127.0.0.1:5762


function finish {
	kill -9 $(ps -eF | grep QG | awk -F' ' '{print $2}')	
	kill -9 $(ps -eF | grep ardu | awk -F' ' '{print $2}')
	kill -9 $(ps -eF | grep mav | awk -F' ' '{print $2}')
}

trap finish EXIT
